# Generated by Django 4.2.4 on 2023-08-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('source_lang', models.CharField(max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
            ],
        ),
    ]
